# Generated by Django 2.2 on 2019-03-01 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('hours', models.IntegerField(default=0)),
                ('dateofWork', models.DateField(default=datetime.datetime(2019, 3, 1, 16, 36, 5, 829403, tzinfo=utc))),
                ('dateofEntry', models.DateField(default=datetime.datetime(2019, 3, 1, 16, 36, 5, 829426, tzinfo=utc))),
            ],
        ),
    ]
